// User/Auth
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const UPDATE_HOSTED_GAMES = 'UPDATE_HOSTED_GAMES';
export const LOAD_USER_LOCATION = 'LOAD_USER_LOCATION';
// export const LOAD_USER_LOCATION_SUCCESS = 'LOAD_USER_LOCATION_SUCCESS';
export const LOAD_USER_LOCATION_DENIED = 'LOAD_USER_LOCATION_DENIED';
export const UPDATE_USER_LOCATION = 'UPDATE_USER_LOCATION';

// HostAGame
export const SELECT_SPORT = 'SELECT_SPORT';
export const UPDATE_GAME_SPORT = 'UPDATE_GAME_SPORT';
export const SELECT_DATE = 'SELECT_DATE';
export const SELECT_TIME = 'SELECT_TIME';
export const UPDATE_MOMENT = 'UPDATE_MOMENT';
export const SELECT_LOCATION = 'SELECT_LOCATION';
export const UPDATE_GAME_LOCATION = 'UPDATE_GAME_LOCATION';