// User/Auth
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const LOAD_USER_LOCATION = 'LOAD_USER_LOCATION';
export const LOAD_USER_LOCATION_SUCCESS = 'LOAD_USER_LOCATION_SUCCESS';
export const LOAD_USER_LOCATION_DENIED = 'LOAD_USER_LOCATION_DENIED';
export const LOAD_USER_LOCATION_FAILURE = 'LOAD_USER_LOCATION_FAILURE';
export const UPDATE_USER_LOCATION = 'UPDATE_USER_LOCATION';
export const ATTEND_GAME = 'ATTEND_GAME';
export const LEAVE_GAME = 'LEAVE_GAME';
export const UPDATE_GAMES_OF_INTEREST = 'UPDATE_GAMES_OF_INTEREST';
export const FOLLOW_SPORT = 'FOLLOW_SPORT';
export const UNFOLLOW_SPORT = 'UNFOLLOW_SPORT';

// HostAGame
export const SELECT_SPORT = 'SELECT_SPORT';
export const UPDATE_GAME_SPORT = 'UPDATE_GAME_SPORT';
export const HOST_A_GAME_NAME_CHANGED = 'HOST_A_GAME_NAME_CHANGED';
export const UPDATE_GAME_NAME = 'UPDATE_GAME_NAME';
export const SELECT_DATE = 'SELECT_DATE';
export const SELECT_TIME = 'SELECT_TIME';
export const UPDATE_MOMENT = 'UPDATE_MOMENT';
export const INIT_REGION = 'INIT_REGION';
export const SELECT_REGION = 'SELECT_REGION';
export const UPDATE_GAME_LOCATION = 'UPDATE_GAME_LOCATION';
export const CLEAR_HOST_A_GAME_FORM = 'CLEAR_HOST_A_GAME_FORM';

// All Games
export const CREATE_GAME = 'CREATE_GAME';
export const UPDATE_GAME = 'UPDATE_GAME';
export const REMOVE_GAME = 'REMOVE_GAME';

// Filter
export const TOGGLE_SOCCER = 'TOGGLE_SOCCER';
export const TOGGLE_BASKETBALL = 'TOGGLE_BASKETBALL';
export const TOGGLE_TENNIS = 'TOGGLE_TENNIS';
export const TOGGLE_GAMES_OF_INTEREST = 'TOGGLE_GAMES_OF_INTEREST';
export const TOGGLE_ATTENDING_GAMES = 'TOGGLE_ATTENDING_GAMES';
export const RESTORE_SAVED_FILTER = 'RESTORE_SAVED_FILTER';
export const SAVE_TMP_FILTER = 'SAVE_TMP_FILTER';

// Misc.
export const NAVIGATE_TO_HOME_FROM_LOADER_SUCCESS = 'NAVIGATE_TO_HOME_FROM_LOADER_SUCCESS';
